name: build

on: [push, pull_request]

jobs:
  build-bin-cross:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            target: mips-unknown-linux-gnu

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: show last commit
        run: |
          git show --summary
      - name: install rust toolchain
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: nightly

      - name: install cross
        run: |
          cargo install cross
      - name: build
        run: |
          cross build --target ${{ matrix.target }} --release
      - name: rename and compress artifacts
        run: |
          mv target/${{ matrix.target }}/release/leaf leaf-${{ matrix.target }}
          #          upx --brute leaf-${{ matrix.target }}
      - name: upload assets
        uses: actions/upload-artifact@v2
        with:
          name: trojan-r-${{ matrix.target }}
          path: trojan-r-${{ matrix.target }}
